# Generated by Django 5.1.4 on 2025-07-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("user", "User"),
                    ("customer", "Customer"),
                ],
                default="user",
                max_length=20,
            ),
        ),
    ]
